// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgsxmgfalxqtgmnreewo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnc3htZ2ZhbHhxdGdtbnJlZXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Mzg0NzIsImV4cCI6MjA2NzExNDQ3Mn0.-w115muVq2MRzbL7yBLGFeEOxTFVP-P1pX1--ez0YLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});